#!/usr/bin/env python3
"""
sdg-prime-multilayer.py
━━━━━━━━━━━━━━━━━━━━━━━
Focused synthetic data generator for the Elastic ML Multilayer Security Workshop.

Generates ONLY the three data streams required for the workshop:

  Stream 1 — APM transaction spans:
    traces-apm-default

  Stream 2 — Edge security: Akamai SIEM + AWS WAF:
    logs-akamai.siem-mortgage
    logs-aws.waf-mortgage

Workshop flow
─────────────
  Step 1  bootstrap-prime-multilayer.py         — templates + data views
  Step 2  THIS SCRIPT  --backfill [--livedata]  — historical + live data
  Step 3  Kibana: create outlier DFA job → clone → classification → inference pipeline
  Step 4  THIS SCRIPT  --livedata-only          — continuous live generation

Key flags
─────────
  --backfill             Generate historical data then stop (or transition to live)
  --livedata             After backfill, continue as a live generator (default: stop after backfill)
  --livedata-only        Skip backfill entirely; start live generation immediately
  --days N               Historical window in days for backfill          (default: 30)
  --apm-traces-per-day N APM traces per weekday                          (default: 500)
  --edge-events-per-day N Edge security events (Akamai + WAF) per day   (default: 2000)
  --anomaly-chance RATE  Fraction of APM traces with geo-anomalous IPs   (default: 0.03)
  --bot-attack-chance R  Fraction of edge events that are bot/attack     (default: 0.05)
  --timezone TZ          IANA timezone for diurnal shaping                (auto-detected)

APM data (traces-apm-default)
──────────────────────────────
  Documents are generated by the same apm_trace_generator module used across
  the full workshop.  Each trace produces ~8–12 documents (transaction + spans
  + optional JVM metrics).  Geo-anomalous traces use foreign IP addresses as
  the client.ip field, which is the primary outlier signal for the DFA job.

  DFA feature fields written to labels.*:
    loan_amount, session_duration_sec, pages_visited,
    docs_downloaded, failed_auth_attempts

Edge security data (Akamai + WAF)
──────────────────────────────────
  Synthetic Akamai SIEM records model bot detections, WAF rule triggers,
  and user-risk scores drawn from realistic ranges.  AWS WAF records model
  ALLOW / BLOCK / COUNT decisions against matching Akamai events.

  The two streams share source.ip values within each synthetic "session"
  so the DFA multi-index job can find correlated signals across them.

  Bot-attack sessions (controlled by --bot-attack-chance) generate:
    • akamai.siem.bot.score         > 80 (high bot probability)
    • akamai.siem.user_risk.score   > 70
    • akamai.siem.user_risk.status  = 1  (risk elevated)
    • aws.waf.action                = BLOCK  (majority)

  Normal sessions use low bot scores, low risk, and ALLOW actions.

Usage
─────
  # Standard: backfill 30 days then go live:
  python sdg-prime-multilayer.py \\
      --host https://localhost:9200 \\
      --user elastic --password changeme \\
      --no-verify-ssl \\
      --backfill --livedata

  # Backfill only:
  python sdg-prime-multilayer.py ... --backfill

  # Live only (skip backfill):
  python sdg-prime-multilayer.py ... --livedata-only

  # Stronger anomaly signal for demo day:
  python sdg-prime-multilayer.py ... --anomaly-chance 0.20 --bot-attack-chance 0.15

  # List available timezones:
  python sdg-prime-multilayer.py --list-timezones
"""

import argparse
import json
import math
import os
import random
import sys
import time
import threading
from datetime import datetime, timedelta, timezone, date
from queue import Queue, Empty

_HERE = os.path.dirname(os.path.realpath(os.path.abspath(__file__)))
sys.path.insert(0, _HERE)

# ── Optional business calendar ─────────────────────────────────────────────────
try:
    from business_calendar import is_us_federal_holiday, is_business_day
    _HAS_CAL = True
except ImportError:
    _HAS_CAL = False

# ── APM trace generator ────────────────────────────────────────────────────────
try:
    import apm_trace_generator as _apm
    from elasticsearch import Elasticsearch
    from elasticsearch.helpers import parallel_bulk
except ImportError as _e:
    if "apm_trace_generator" in str(_e):
        print(f"ERROR: apm_trace_generator.py not found in {_HERE}")
        print("  Ensure sdg-prime-multilayer.py is in the same directory.")
    else:
        print("ERROR: elasticsearch-py not installed.  Run: pip install elasticsearch")
    sys.exit(1)

import multiprocessing as _mp

# ══════════════════════════════════════════════════════════════════════════════
# Constants
# ══════════════════════════════════════════════════════════════════════════════

DEFAULT_DAYS           = 30
DEFAULT_APM_TPD        = 500      # APM traces per weekday
DEFAULT_EDGE_EPD       = 2000     # edge security events per day (Akamai + WAF combined)
DEFAULT_ANOMALY        = 0.03     # fraction of APM traces with anomalous geo
DEFAULT_BOT_ATTACK     = 0.05     # fraction of edge events that are bot/attack sessions

_CPU_CORES             = _mp.cpu_count() or 4
DEFAULT_WORKERS        = min(_CPU_CORES * 2, 32)
DEFAULT_PB_THREADS     = min(4, max(2, _CPU_CORES // 4))
DEFAULT_BULK_SIZE_APM  = 200
DEFAULT_BULK_SIZE_EDGE = 500
DEFAULT_PB_QUEUE       = 4

_SERVICE_NAMES    = list(_apm.SERVICES.keys())
_SERVICE_WEIGHTS  = [40, 20, 15, 15, 10]
_METRICS_EVERY    = 30

# Diurnal weights — business-hours peak at 13:00
_WORKDAY_W = [
    0.00, 0.00, 0.00, 0.00, 0.00, 0.01,
    0.03, 0.15, 0.55, 0.80, 0.95, 1.00,
    0.98, 0.95, 0.85, 0.75, 0.60, 0.40,
    0.20, 0.08, 0.03, 0.01, 0.00, 0.00,
]
_WEEKEND_W = [
    0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
    0.01, 0.02, 0.03, 0.04, 0.04, 0.04,
    0.04, 0.04, 0.03, 0.03, 0.02, 0.02,
    0.01, 0.01, 0.00, 0.00, 0.00, 0.00,
]

# Realistic geo data for normal (US home-city) and anomalous (foreign) sessions
_NORMAL_GEOS = [
    {"city": "New York",       "country": "US", "lat": 40.71, "lon": -74.01},
    {"city": "Los Angeles",    "country": "US", "lat": 34.05, "lon": -118.24},
    {"city": "Chicago",        "country": "US", "lat": 41.88, "lon": -87.63},
    {"city": "Houston",        "country": "US", "lat": 29.76, "lon": -95.37},
    {"city": "Phoenix",        "country": "US", "lat": 33.45, "lon": -112.07},
    {"city": "Philadelphia",   "country": "US", "lat": 39.95, "lon": -75.17},
    {"city": "San Antonio",    "country": "US", "lat": 29.42, "lon": -98.49},
    {"city": "San Diego",      "country": "US", "lat": 32.72, "lon": -117.16},
    {"city": "Dallas",         "country": "US", "lat": 32.78, "lon": -96.80},
    {"city": "San Jose",       "country": "US", "lat": 37.34, "lon": -121.89},
]

_ANOMALOUS_GEOS = [
    {"city": "Lagos",          "country": "NG", "lat":  6.52, "lon":  3.38},
    {"city": "Moscow",         "country": "RU", "lat": 55.75, "lon": 37.62},
    {"city": "Beijing",        "country": "CN", "lat": 39.91, "lon": 116.39},
    {"city": "Bucharest",      "country": "RO", "lat": 44.43, "lon": 26.10},
    {"city": "Minsk",          "country": "BY", "lat": 53.90, "lon": 27.57},
    {"city": "Tehran",         "country": "IR", "lat": 35.69, "lon": 51.39},
    {"city": "Pyongyang",      "country": "KP", "lat": 39.01, "lon": 125.75},
]

# WAF action distribution: normal vs attack sessions
_WAF_NORMAL_ACTIONS  = ["ALLOW"] * 90 + ["COUNT"] * 8 + ["BLOCK"] * 2
_WAF_ATTACK_ACTIONS  = ["BLOCK"] * 60 + ["COUNT"] * 25 + ["ALLOW"] * 15

# Akamai rule IDs and tags (realistic subset)
_AKAMAI_RULE_IDS = [
    "950001", "950002", "950005", "950007", "950008", "950009",
    "950010", "950018", "950019", "950109", "960024", "960901",
    "981175", "981243", "981244", "981246", "981257", "981317",
    "990012", "990902",
]
_AKAMAI_RULE_TAGS = [
    "WEB_ATTACK/SQL_INJECTION", "WEB_ATTACK/XSS", "WEB_ATTACK/RFI",
    "WEB_ATTACK/LFI", "AUTOMATED/BOT", "AUTOMATED/SCRAPER",
    "THREAT_INTEL/KNOWN_MALICIOUS_IP", "THREAT_INTEL/KNOWN_PROXY",
    "AUTOMATED/SCANNER", "WEB_ATTACK/COMMAND_INJECTION",
]

# Akamai config / policy IDs (static — one per "deployment")
_AKAMAI_CONFIG_ID  = "12345"
_AKAMAI_POLICY_ID  = "LNDP_STG"

# URL paths observed in edge traffic
_EDGE_PATHS = [
    "/api/v1/mortgage/apply",    "/api/v1/mortgage/status",
    "/api/v1/auth/login",        "/api/v1/auth/logout",
    "/api/v1/documents/upload",  "/api/v1/documents/list",
    "/api/v1/rates/current",     "/api/v1/underwriting/submit",
    "/login", "/dashboard", "/apply", "/rates",
    "/.env", "/admin/config", "/wp-login.php",           # attack probes
    "/api/v1/admin/users",       "/actuator/health",
]

_EDGE_DOMAINS = ["app.lendpath.io", "api.lendpath.io", "portal.lendpath.io"]

_USER_AGENTS_NORMAL = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_4) AppleWebKit/605.1.15",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15",
    "Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/114",
]
_USER_AGENTS_BOT = [
    "python-requests/2.28.2",
    "Go-http-client/2.0",
    "curl/7.88.1",
    "Scrapy/2.9.0",
    "axios/1.3.4",
    "masscan/1.3",
    "zgrab/0.x",
]

# ══════════════════════════════════════════════════════════════════════════════
# Timezone / calendar helpers
# ══════════════════════════════════════════════════════════════════════════════

def _local_tz():
    try:
        import tzlocal
        return tzlocal.get_localzone()
    except Exception:
        import time as _t
        offset = -_t.timezone if not _t.daylight else -_t.altzone
        return timezone(timedelta(seconds=offset))


def resolve_tz(name):
    if not name:
        return _local_tz()
    try:
        import zoneinfo
        return zoneinfo.ZoneInfo(name)
    except Exception:
        pass
    try:
        import pytz
        return pytz.timezone(name)
    except Exception:
        pass
    print(f"  ⚠ Unknown timezone {name!r} — using local")
    return _local_tz()


def tz_str(tz):
    return getattr(tz, "key", getattr(tz, "zone", str(tz)))


def list_timezones():
    try:
        import zoneinfo
        zones = sorted(zoneinfo.available_timezones())
    except ImportError:
        try:
            import pytz
            zones = sorted(pytz.all_timezones)
        except ImportError:
            print("Install zoneinfo or pytz to list timezones.")
            return
    cols, w = 3, 35
    print(f"\n{len(zones)} timezones:\n")
    for i in range(0, len(zones), cols):
        print("  " + "".join(f"{z:<{w}}" for z in zones[i:i+cols]))
    print()


def _is_reduced_day(d):
    if _HAS_CAL:
        return not is_business_day(d) or is_us_federal_holiday(d)
    return d.weekday() >= 5


def _day_factor(d):
    return 0.15 if _is_reduced_day(d) else 1.0


def _hour_weights(d):
    return _WEEKEND_W if _is_reduced_day(d) else _WORKDAY_W


def _hour_counts(target, weights):
    total_w = sum(weights)
    counts, allocated = [], 0
    for w in weights:
        n = round(target * w / total_w) if total_w > 0 else 0
        counts.append(n)
        allocated += n
    counts[13] += target - allocated   # remainder at peak hour
    return counts


# ══════════════════════════════════════════════════════════════════════════════
# Timestamp generators
# ══════════════════════════════════════════════════════════════════════════════

def _fmt_ts(dt_utc):
    return dt_utc.strftime("%Y-%m-%dT%H:%M:%S.") + f"{dt_utc.microsecond//1000:03d}Z"


def timestamps_for_day(day_dt, count, tz):
    """Yield ISO timestamp strings distributed by diurnal pattern."""
    weights   = _hour_weights(day_dt)
    counts    = _hour_counts(count, weights)
    day_start = datetime(day_dt.year, day_dt.month, day_dt.day, tzinfo=tz)
    for hour, n in enumerate(counts):
        if n <= 0:
            continue
        h_utc = (day_start + timedelta(hours=hour)).astimezone(timezone.utc)
        for _ in range(n):
            ts = h_utc + timedelta(seconds=random.uniform(0, 3599))
            yield _fmt_ts(ts)


def timestamps_from_now(count, tz):
    """Yield (ts_string, sleep_seconds) for live generation of today's remainder."""
    now_utc      = datetime.now(timezone.utc)
    today_local  = now_utc.astimezone(tz).date()
    weights      = list(_hour_weights(today_local))
    current_hour = now_utc.astimezone(tz).hour
    for h in range(current_hour):
        weights[h] = 0

    if sum(weights) == 0 or count <= 0:
        return

    counts    = _hour_counts(count, weights)
    day_start = datetime(today_local.year, today_local.month, today_local.day, tzinfo=tz)
    events    = []
    for hour, n in enumerate(counts):
        if n <= 0:
            continue
        h_utc = (day_start + timedelta(hours=hour)).astimezone(timezone.utc)
        for _ in range(n):
            ts = h_utc + timedelta(seconds=random.uniform(0, 3599))
            if ts < now_utc:
                ts = now_utc + timedelta(seconds=random.uniform(1, 30))
            events.append(ts)
    events.sort()

    prev = now_utc
    for ts in events:
        sleep_s = max(0.0, (ts - prev).total_seconds())
        yield _fmt_ts(ts), sleep_s
        prev = ts


# ══════════════════════════════════════════════════════════════════════════════
# APM document generation
# ══════════════════════════════════════════════════════════════════════════════

def _inject_timestamp(actions, ts_iso):
    """Overwrite @timestamp (and timestamp.us) on every doc in an action list."""
    try:
        dt    = datetime.strptime(ts_iso, "%Y-%m-%dT%H:%M:%S.%fZ").replace(tzinfo=timezone.utc)
        ts_us = int(dt.timestamp() * 1_000_000)
    except ValueError:
        ts_us = int(datetime.now(timezone.utc).timestamp() * 1_000_000)

    for action in actions:
        src = action.get("_source", {})
        if "@timestamp" in src:
            src["@timestamp"] = ts_iso
        if "timestamp" in src and isinstance(src["timestamp"], dict):
            src["timestamp"]["us"] = ts_us
    return actions


def _make_apm_actions(ts_iso, anomaly_chance, metrics_counter):
    """
    Generate one APM trace (transaction + spans) and optionally JVM metrics.
    Returns a list of bulk action dicts ready for parallel_bulk.
    """
    svc_name = random.choices(_SERVICE_NAMES, weights=_SERVICE_WEIGHTS, k=1)[0]
    actions  = _apm.generate_trace(svc_name, anomaly_chance=anomaly_chance)
    actions  = _inject_timestamp(actions, ts_iso)

    metrics_counter[0] += 1
    if metrics_counter[0] % _METRICS_EVERY == 0:
        for svc in _SERVICE_NAMES:
            actions.extend(_apm.generate_metrics(svc, ts_iso=ts_iso))

    return actions


# ══════════════════════════════════════════════════════════════════════════════
# Edge security document generation
# ══════════════════════════════════════════════════════════════════════════════

def _random_ip(geo):
    """
    Return a plausible random IP in a /8 subnet roughly associated with the
    given country code.  Not geo-accurate — just distinctive enough that the
    ML model sees a consistent per-country distribution.
    """
    # Use a deterministic prefix per country so the same country always maps to
    # the same subnet family.  This makes the geo signal more learnable.
    _prefix = {
        "US": (17,  40),   "NG": (197, 212),
        "RU": (178, 185),  "CN": (36,  123),
        "RO": (5,   79),   "BY": (178, 193),
        "IR": (5,   185),  "KP": (175, 175),
    }
    lo, hi = _prefix.get(geo.get("country", "US"), (10, 200))
    a = random.randint(lo, hi)
    b, c, d = random.randint(0, 255), random.randint(0, 255), random.randint(1, 254)
    return f"{a}.{b}.{c}.{d}"


def _akamai_doc(ts_iso, is_attack, geo):
    """Build one Akamai SIEM document."""
    ip = _random_ip(geo)

    if is_attack:
        bot_score       = random.randint(70, 100)
        risk_score      = random.randint(65, 100)
        risk_status     = 1
        rule_actions    = random.choice(["alert", "deny"])
        rule_tags       = random.sample(_AKAMAI_RULE_TAGS, k=random.randint(1, 3))
        rule_ids        = random.sample(_AKAMAI_RULE_IDS,  k=random.randint(1, 2))
        ua              = random.choice(_USER_AGENTS_BOT)
        status_code     = random.choice([403, 429, 400, 503, 200])
    else:
        bot_score       = random.randint(0, 25)
        risk_score      = random.randint(0, 30)
        risk_status     = 0
        rule_actions    = "none"
        rule_tags       = []
        rule_ids        = []
        ua              = random.choice(_USER_AGENTS_NORMAL)
        status_code     = random.choice([200, 200, 200, 201, 304, 404])

    path   = random.choice(_EDGE_PATHS)
    domain = random.choice(_EDGE_DOMAINS)

    return {
        "_op_type": "create",
        "_index":   "logs-akamai.siem-mortgage",
        "_source": {
            "@timestamp":    ts_iso,
            "event": {
                "kind":     "event",
                "category": "intrusion_detection" if is_attack else "network",
                "type":     "denied" if is_attack else "allowed",
                "outcome":  "failure" if is_attack else "success",
            },
            "source": {
                "ip":      ip,
                "address": ip,
                "geo": {
                    "location": {"lat": geo["lat"], "lon": geo["lon"]},
                    "country_iso_code": geo["country"],
                    "city_name":        geo["city"],
                    "region_name":      geo.get("region", geo["city"]),
                },
            },
            "client": {"ip": ip, "address": ip},
            "http": {
                "request":  {"method": random.choice(["GET", "POST", "PUT", "DELETE"])},
                "response": {
                    "status_code": status_code,
                    "body": {"bytes": random.randint(200, 50_000)},
                },
                "version": "1.1",
            },
            "url": {
                "full":   f"https://{domain}{path}",
                "path":   path,
                "domain": domain,
                "port":   443,
            },
            "user_agent": {"original": ua},
            "akamai": {
                "siem": {
                    "config_id":    _AKAMAI_CONFIG_ID,
                    "policy_id":    _AKAMAI_POLICY_ID,
                    "rule_actions": rule_actions,
                    "rule_tags":    rule_tags,
                    "bot": {
                        "score":            bot_score,
                        "response_segment": random.randint(0, 5),
                    },
                    "user_risk": {
                        "score":  risk_score,
                        "status": risk_status,
                        "allow":  0 if is_attack else 1,
                        "uuid":   f"{random.randint(100000,999999):x}-"
                                  f"{random.randint(1000,9999):x}-"
                                  f"{random.randint(1000,9999):x}",
                        "trust":  {"ugp": ""},
                        "general": {
                            "duc_1d": str(random.randint(1, 50)) if is_attack else "0",
                            "duc_1h": str(random.randint(1, 10)) if is_attack else "0",
                        },
                    },
                    "client_data": {
                        "app_bundle_id":  "",
                        "app_version":    "",
                        "sdk_version":    "",
                        "telemetry_type": 0,
                    },
                }
            },
        },
    }


def _waf_doc(ts_iso, is_attack, geo, akamai_ip):
    """
    Build one AWS WAF document that correlates with the paired Akamai event.
    Uses the same source IP so cross-index DFA can find the correlation.
    """
    action  = random.choice(_WAF_ATTACK_ACTIONS if is_attack else _WAF_NORMAL_ACTIONS)
    path    = random.choice(_EDGE_PATHS)
    domain  = random.choice(_EDGE_DOMAINS)
    ua      = random.choice(_USER_AGENTS_BOT if is_attack else _USER_AGENTS_NORMAL)
    sc      = random.choice([403, 400] if action == "BLOCK" else [200, 201, 304])

    return {
        "_op_type": "create",
        "_index":   "logs-aws.waf-mortgage",
        "_source": {
            "@timestamp": ts_iso,
            "event": {
                "kind":    "event",
                "outcome": "failure" if action == "BLOCK" else "success",
            },
            "source": {"ip": akamai_ip},
            "http": {
                "request":  {"method": random.choice(["GET", "POST"])},
                "response": {
                    "status_code": sc,
                    "body": {"bytes": random.randint(100, 20_000)},
                },
                "version": "1.1",
            },
            "url": {
                "full": f"https://{domain}{path}",
                "path": path,
            },
            "aws": {
                "waf": {
                    "arn":            f"arn:aws:wafv2:us-east-1:123456789012:regional/webacl/LendPath/{random.randint(1,9999)}",
                    "id":             f"waf-{random.randint(10000,99999)}",
                    "format_version": "1.0",
                    "action":         action,
                    "request": {
                        "headers": {
                            "User-Agent": ua,
                            "Host":       domain,
                        }
                    },
                },
                "s3": {
                    "bucket": {"arn": "arn:aws:s3:::lendpath-waf-logs", "name": "lendpath-waf-logs"},
                    "object": {"key": f"waf/{datetime.utcnow().strftime('%Y/%m/%d')}/log.gz"},
                },
            },
        },
    }


def _make_edge_actions(ts_iso, is_attack):
    """
    Generate one correlated pair: one Akamai SIEM event + one AWS WAF event.
    Both share the same source IP so the DFA multi-index job finds them.
    Returns a list of two bulk action dicts.
    """
    geo       = random.choice(_ANOMALOUS_GEOS) if is_attack else random.choice(_NORMAL_GEOS)
    akamai    = _akamai_doc(ts_iso, is_attack, geo)
    akamai_ip = akamai["_source"]["source"]["ip"]
    waf       = _waf_doc(ts_iso, is_attack, geo, akamai_ip)
    return [akamai, waf]


# ══════════════════════════════════════════════════════════════════════════════
# Backfill workers
# ══════════════════════════════════════════════════════════════════════════════

def _apm_day_worker(es, day_dt, trace_count, anomaly_chance,
                    bulk_size, pb_threads, pb_queue, progress_q, tz):
    metrics_counter = [0]

    def _gen():
        for ts in timestamps_for_day(day_dt, trace_count, tz):
            yield from _make_apm_actions(ts, anomaly_chance, metrics_counter)

    try:
        for ok, info in parallel_bulk(
            es, _gen(),
            thread_count=pb_threads, chunk_size=bulk_size,
            queue_size=pb_queue, raise_on_error=False,
            raise_on_exception=False, request_timeout=120,
        ):
            progress_q.put(("APM", "OK" if ok else f"ERR:{info}"))
    except Exception as e:
        progress_q.put(("APM", f"ERR:{day_dt}:{e}"))


def _edge_day_worker(es, day_dt, event_count, bot_attack_chance,
                     bulk_size, pb_threads, pb_queue, progress_q, tz):
    def _gen():
        for ts in timestamps_for_day(day_dt, event_count, tz):
            is_attack = random.random() < bot_attack_chance
            yield from _make_edge_actions(ts, is_attack)

    try:
        for ok, info in parallel_bulk(
            es, _gen(),
            thread_count=pb_threads, chunk_size=bulk_size,
            queue_size=pb_queue, raise_on_error=False,
            raise_on_exception=False, request_timeout=120,
        ):
            progress_q.put(("EDGE", "OK" if ok else f"ERR:{info}"))
    except Exception as e:
        progress_q.put(("EDGE", f"ERR:{day_dt}:{e}"))


# ══════════════════════════════════════════════════════════════════════════════
# Backfill orchestration
# ══════════════════════════════════════════════════════════════════════════════

def run_backfill(host, user, password, verify_ssl,
                 days, apm_tpd, edge_epd, anomaly_chance, bot_attack_chance, tz,
                 workers, bulk_size_apm, bulk_size_edge, pb_threads, pb_queue):
    """
    Generate historical data for all three streams in parallel.
    APM and EDGE work-queues run concurrently using worker thread pools.
    Returns (backfill_days, apm_tpd, today_apm_written) for use by live generator.
    """
    ssl_opts = {"verify_certs": verify_ssl, "ssl_show_warn": False}
    if not verify_ssl:
        ssl_opts["ssl_assert_fingerprint"] = None
    es = Elasticsearch(host, basic_auth=(user, password), **ssl_opts)

    today     = datetime.now(tz).date()
    start_day = today - timedelta(days=days)
    tz_name   = tz_str(tz)

    # Build per-day schedule (excludes today — today is handled by live mode)
    schedule = []
    for d in range(days):
        day = start_day + timedelta(days=d)
        schedule.append({
            "day":        day,
            "apm_count":  max(1, round(apm_tpd  * _day_factor(day))),
            "edge_count": max(1, round(edge_epd * _day_factor(day))),
        })

    est_docs_per_trace = 10
    total_apm_traces   = sum(s["apm_count"]  for s in schedule)
    total_edge_events  = sum(s["edge_count"] for s in schedule)
    total_docs         = total_apm_traces * est_docs_per_trace + total_edge_events * 2

    print(f"\n{'='*70}")
    print(f"  SDG-Prime Multilayer — Historical Backfill")
    print(f"{'='*70}")
    print(f"  Streams:        traces-apm-default")
    print(f"                  logs-akamai.siem-mortgage")
    print(f"                  logs-aws.waf-mortgage")
    print(f"  Days:           {days}  ({start_day} → {today - timedelta(days=1)})")
    print(f"  APM (weekday):  {apm_tpd:,} traces/day  (~{apm_tpd*est_docs_per_trace:,} docs)")
    print(f"  Edge (weekday): {edge_epd:,} events/day  ({edge_epd*2:,} docs: Akamai + WAF)")
    print(f"  Anomaly chance: {anomaly_chance:.0%}  geo-anomalous APM traces")
    print(f"  Bot/attack:     {bot_attack_chance:.0%}  of edge events are attack sessions")
    print(f"  Timezone:       {tz_name}")
    print(f"  ~Total docs:    {total_docs:,}")
    print(f"  CPU cores:      {_CPU_CORES} → workers={workers}, pb_threads={pb_threads}")
    print()

    if "utc" in tz_name.lower() or tz_name in ("UTC", "Etc/UTC", "GMT"):
        print("  ⚠ Timezone is UTC — diurnal peak may appear shifted in Kibana.")
        print("    Use --timezone 'America/New_York' to align with local business hours.\n")

    # Pre-flight: verify data streams exist
    print("  Checking data streams…")
    for ds in ["traces-apm-default", "logs-akamai.siem-mortgage", "logs-aws.waf-mortgage"]:
        try:
            es.indices.get_data_stream(name=ds)
            print(f"    ✓ {ds}")
        except Exception:
            print(f"    ✗ {ds} — NOT FOUND. Run bootstrap-prime-multilayer.py first.")
    print()
    print("  Press Ctrl+C to stop.\n")

    progress_q    = Queue()
    start_time    = time.time()
    apm_ok = apm_err = edge_ok = edge_err = 0
    _last_print   = [time.time()]

    def printer():
        nonlocal apm_ok, apm_err, edge_ok, edge_err
        while True:
            try:
                item = progress_q.get(timeout=1)
                if item is None:
                    break
                stream, result = item
                ok = result == "OK"
                if stream == "APM":
                    if ok: apm_ok  += 1
                    else:  apm_err += 1
                else:
                    if ok: edge_ok += 1
                    else:  edge_err += 1

                if not ok:
                    errs = apm_err + edge_err
                    if errs <= 50:
                        print(f"  ⚠ [{stream}] {result[4:]}")
                    elif errs == 51:
                        print("  (further errors suppressed)")

                now = time.time()
                if now - _last_print[0] >= 10:
                    elapsed = now - start_time
                    total   = apm_ok + edge_ok
                    rate    = total / elapsed if elapsed > 0 else 0
                    eta     = (total_docs - total) / rate if rate > 0 else 0
                    pct     = min(total / total_docs * 100, 100) if total_docs else 0
                    errs    = apm_err + edge_err
                    print(f"  [{pct:5.1f}%] {total:>10,}/~{total_docs:,}"
                          f"  |  {rate:>8,.0f} docs/sec"
                          f"  |  ETA {int(eta//3600):02d}h{int((eta%3600)//60):02d}m"
                          + (f"  |  {errs} errs" if errs else "")
                          + f"  [APM {apm_ok:,}  EDGE {edge_ok:,}]")
                    _last_print[0] = now
            except Empty:
                continue

    t_print = threading.Thread(target=printer, daemon=True)
    t_print.start()

    # ── APM and EDGE work queues (run concurrently) ───────────────────────────
    apm_q  = Queue()
    edge_q = Queue()
    for s in schedule:
        apm_q.put((s["day"], s["apm_count"]))
        edge_q.put((s["day"], s["edge_count"]))

    apm_workers_n  = max(1, workers // 2)
    edge_workers_n = max(1, workers - apm_workers_n)

    def _apm_worker():
        while True:
            try:
                day_dt, count = apm_q.get_nowait()
            except Empty:
                return
            try:
                _apm_day_worker(es, day_dt, count, anomaly_chance,
                                bulk_size_apm, pb_threads, pb_queue, progress_q, tz)
            except Exception as e:
                progress_q.put(("APM", f"ERR:{e}"))
            finally:
                apm_q.task_done()

    def _edge_worker():
        while True:
            try:
                day_dt, count = edge_q.get_nowait()
            except Empty:
                return
            try:
                _edge_day_worker(es, day_dt, count, bot_attack_chance,
                                 bulk_size_edge, pb_threads, pb_queue, progress_q, tz)
            except Exception as e:
                progress_q.put(("EDGE", f"ERR:{e}"))
            finally:
                edge_q.task_done()

    threads = (
        [threading.Thread(target=_apm_worker, daemon=True) for _ in range(min(apm_workers_n, days))]
        + [threading.Thread(target=_edge_worker, daemon=True) for _ in range(min(edge_workers_n, days))]
    )
    for t in threads:
        t.start()
    try:
        for t in threads:
            t.join()
    except KeyboardInterrupt:
        print("\n\nBackfill interrupted.")

    progress_q.put(None)
    t_print.join(timeout=10)

    elapsed = time.time() - start_time
    h, m, s = int(elapsed//3600), int((elapsed%3600)//60), int(elapsed%60)
    total_indexed = apm_ok + edge_ok
    rate          = total_indexed / elapsed if elapsed > 0 else 0
    errs          = apm_err + edge_err

    print(f"\n{'='*70}")
    print(f"  Backfill complete  —  {h:02d}h {m:02d}m {s:02d}s")
    print(f"  {'─'*66}")
    print(f"  APM  docs: {apm_ok:>12,}" + (f"  [{apm_err} errors]"  if apm_err  else ""))
    print(f"  EDGE docs: {edge_ok:>12,}" + (f"  [{edge_err} errors]" if edge_err else ""))
    print(f"  Total:     {total_indexed:>12,}  |  {rate:,.0f} docs/sec")
    if errs:
        print(f"  Errors:    {errs}")
    print()
    print(f"  Signals embedded:")
    print(f"    APM geo-anomalous traces: ~{anomaly_chance:.0%} "
          f"(~{round(total_apm_traces * anomaly_chance):,} of {total_apm_traces:,} traces)")
    print(f"    Edge bot/attack sessions: ~{bot_attack_chance:.0%} "
          f"(~{round(total_edge_events * bot_attack_chance):,} of {total_edge_events:,} events)")
    print(f"{'='*70}")

    # today excluded — return 0 so live mode generates a full day quota
    return days, apm_tpd, edge_epd, 0, 0


# ══════════════════════════════════════════════════════════════════════════════
# Live generation
# ══════════════════════════════════════════════════════════════════════════════

def run_live(es, apm_tpd, edge_epd, anomaly_chance, bot_attack_chance,
             backfill_days,
             backfill_today_apm, backfill_today_edge,
             bulk_size_apm, bulk_size_edge, pb_threads, pb_queue, tz):
    """
    Continuous live generation for all three streams.
    Generates today's remaining quota at the natural diurnal rate, then
    continues generating full days as midnight rolls.
    """
    tz_name = tz_str(tz)
    print(f"\n{'='*70}")
    print(f"  Live generation — {tz_name}")
    print(f"  APM:  ~{apm_tpd:,} traces/weekday  |  anomaly: {anomaly_chance:.0%}")
    print(f"  Edge: ~{edge_epd:,} events/weekday  |  bot/attack: {bot_attack_chance:.0%}")
    print(f"  Backfill covered: {backfill_days} days")
    print(f"  Press Ctrl+C to stop.\n")

    metrics_counter = [0]
    indexed_live    = 0
    error_count     = 0
    start_time      = time.time()
    _last_status    = time.time()
    current_day     = datetime.now(tz).date()

    apm_target  = max(0, round(apm_tpd  * _day_factor(current_day)) - backfill_today_apm)
    edge_target = max(0, round(edge_epd * _day_factor(current_day)) - backfill_today_edge)

    end_of_today = (
        datetime(current_day.year, current_day.month, current_day.day, tzinfo=tz)
        + timedelta(days=1)
    ).astimezone(timezone.utc)

    print(f"  Today ({current_day}):")
    print(f"    APM  backfill wrote: {backfill_today_apm:>6,}  remaining: {apm_target:>6,}")
    print(f"    EDGE backfill wrote: {backfill_today_edge:>6,}  remaining: {edge_target:>6,}")
    print(f"    Day rolls at: {end_of_today.strftime('%H:%M:%S UTC')}\n")

    def _status():
        nonlocal _last_status
        if time.time() - _last_status >= 30:
            print(f"  [{indexed_live:,} live docs"
                  + (f", {error_count} errors" if error_count else "") + "]")
            _last_status = time.time()

    def _index_batch(actions):
        nonlocal indexed_live, error_count
        try:
            for ok, info in parallel_bulk(
                es, actions,
                thread_count=1, chunk_size=len(actions),
                queue_size=1, raise_on_error=False,
                raise_on_exception=False, request_timeout=30,
            ):
                if ok:
                    indexed_live += 1
                else:
                    error_count += 1
        except Exception:
            error_count += 1

    # ── Merge APM + EDGE event streams for today, sorted by timestamp ─────────
    # We interleave both streams so that correlated events (same session IP)
    # arrive in timestamp order — more realistic for streaming ingest.

    apm_events  = list(timestamps_from_now(apm_target,  tz))  # [(ts, sleep_s), ...]
    edge_events = list(timestamps_from_now(edge_target, tz))

    # Merge and sort by timestamp; tag each event with its stream
    combined = (
        [(ts, s, "APM")  for ts, s in apm_events] +
        [(ts, s, "EDGE") for ts, s in edge_events]
    )
    combined.sort(key=lambda x: x[0])

    prev_time = time.time()
    for ts_str, sleep_s, stream in combined:
        now = time.time()
        actual_sleep = max(0.0, sleep_s - (now - prev_time))
        if actual_sleep > 0:
            time.sleep(min(actual_sleep, 5.0))
        prev_time = time.time()

        if stream == "APM":
            actions = _make_apm_actions(ts_str, anomaly_chance, metrics_counter)
        else:
            is_attack = random.random() < bot_attack_chance
            actions   = _make_edge_actions(ts_str, is_attack)

        _index_batch(actions)
        _status()

    # ── Full days after midnight ───────────────────────────────────────────────
    print(f"\n  Today's quota complete — entering continuous daily mode.")
    print(f"  Ctrl+C to stop.\n")

    while True:
        now_local   = datetime.now(tz)
        today       = now_local.date()
        apm_count   = max(1, round(apm_tpd  * _day_factor(today)))
        edge_count  = max(1, round(edge_epd * _day_factor(today)))
        midnight    = (datetime(today.year, today.month, today.day, tzinfo=tz)
                       + timedelta(days=1)).astimezone(timezone.utc)
        secs_left   = max(1, (midnight - datetime.now(timezone.utc)).total_seconds())
        total_day   = apm_count + edge_count
        sleep_per   = secs_left / total_day

        try:
            while datetime.now(tz).date() == today:
                ts_str = _fmt_ts(datetime.now(timezone.utc))
                # Alternate APM and EDGE events at a 1:4 ratio (1 trace ≈ 10 docs,
                # 1 edge pair = 2 docs; keeping the ratio ~equal in doc count)
                stream  = "APM" if random.random() < (apm_count / (apm_count + edge_count)) else "EDGE"
                if stream == "APM":
                    actions = _make_apm_actions(ts_str, anomaly_chance, metrics_counter)
                else:
                    is_attack = random.random() < bot_attack_chance
                    actions   = _make_edge_actions(ts_str, is_attack)
                _index_batch(actions)
                time.sleep(max(0.001, sleep_per))
                _status()
        except KeyboardInterrupt:
            break

    elapsed = time.time() - start_time
    h, m, s = int(elapsed//3600), int((elapsed%3600)//60), int(elapsed%60)
    print(f"\n{'='*70}")
    print(f"  Live generation stopped after {h:02d}h {m:02d}m {s:02d}s")
    print(f"  Live docs indexed: {indexed_live:,}"
          + (f"  |  {error_count} errors" if error_count else ""))
    print(f"{'='*70}\n")


# ══════════════════════════════════════════════════════════════════════════════
# Entry point
# ══════════════════════════════════════════════════════════════════════════════

def main():
    p = argparse.ArgumentParser(
        description=(
            "SDG-Prime Multilayer: generates APM spans + Akamai/WAF edge security data "
            "for the Elastic ML Multilayer Security Workshop."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples
────────
  # Backfill 30 days then transition to live generation:
  python sdg-prime-multilayer.py \\
      --host https://localhost:9200 \\
      --user elastic --password changeme --no-verify-ssl \\
      --backfill --livedata

  # Backfill only:
  python sdg-prime-multilayer.py ... --backfill

  # Live only (skip backfill):
  python sdg-prime-multilayer.py ... --livedata-only

  # Higher volume, stronger signal for demo day:
  python sdg-prime-multilayer.py ... \\
      --days 14 \\
      --apm-traces-per-day 2000 \\
      --edge-events-per-day 5000 \\
      --anomaly-chance 0.20 \\
      --bot-attack-chance 0.15 \\
      --timezone America/New_York \\
      --backfill --livedata

  # List available timezones:
  python sdg-prime-multilayer.py --list-timezones
        """
    )
    p.add_argument("--host",                   default="https://localhost:9200")
    p.add_argument("--user",                   default="elastic")
    p.add_argument("--password",               default="changeme")
    p.add_argument("--no-verify-ssl",          action="store_true")

    # Volume controls
    p.add_argument("--days", "-d",             type=int,   default=DEFAULT_DAYS,
                   help=f"Historical window for backfill in days (default: {DEFAULT_DAYS})")
    p.add_argument("--apm-traces-per-day",     type=int,   default=DEFAULT_APM_TPD,
                   metavar="N",
                   help=f"APM traces per weekday (default: {DEFAULT_APM_TPD:,}). "
                        f"Each trace produces ~10 docs.")
    p.add_argument("--edge-events-per-day",    type=int,   default=DEFAULT_EDGE_EPD,
                   metavar="N",
                   help=f"Edge security events per day (default: {DEFAULT_EDGE_EPD:,}). "
                        f"Each event generates 1 Akamai doc + 1 WAF doc.")

    # Signal controls
    p.add_argument("--anomaly-chance",         type=float, default=DEFAULT_ANOMALY,
                   metavar="RATE",
                   help=f"Fraction of APM traces with geo-anomalous IPs (default: {DEFAULT_ANOMALY}). "
                        f"Raise to 0.15–0.30 for stronger outlier signals.")
    p.add_argument("--bot-attack-chance",      type=float, default=DEFAULT_BOT_ATTACK,
                   metavar="RATE",
                   help=f"Fraction of edge events that are bot/attack sessions (default: {DEFAULT_BOT_ATTACK}). "
                        f"Attack sessions have high bot scores, elevated risk, and BLOCK actions.")

    # Execution mode
    p.add_argument("--backfill",               action="store_true",
                   help="Run the historical backfill. "
                        "Add --livedata to transition to live generation when done. "
                        "Without either flag, both backfill and live are run.")
    p.add_argument("--livedata",               action="store_true",
                   help="After backfill, continue as a live generator. "
                        "Only meaningful combined with --backfill.")
    p.add_argument("--livedata-only",          action="store_true",
                   help="Skip backfill; start live generation immediately.")

    # Performance tuning
    p.add_argument("--workers",   "-w",        type=int,   default=DEFAULT_WORKERS,
                   help=f"Worker threads for backfill (default: {DEFAULT_WORKERS})")
    p.add_argument("--bulk-size-apm",          type=int,   default=DEFAULT_BULK_SIZE_APM,
                   help=f"Bulk request size for APM docs (default: {DEFAULT_BULK_SIZE_APM})")
    p.add_argument("--bulk-size-edge",         type=int,   default=DEFAULT_BULK_SIZE_EDGE,
                   help=f"Bulk request size for edge docs (default: {DEFAULT_BULK_SIZE_EDGE})")
    p.add_argument("--pb-threads",             type=int,   default=DEFAULT_PB_THREADS,
                   help=f"parallel_bulk threads per worker (default: {DEFAULT_PB_THREADS})")
    p.add_argument("--pb-queue",               type=int,   default=DEFAULT_PB_QUEUE,
                   help=f"parallel_bulk queue depth (default: {DEFAULT_PB_QUEUE})")

    p.add_argument("--timezone",               default=None, metavar="TZ",
                   help="IANA timezone for diurnal shaping (default: system local). "
                        "Use --list-timezones to see options.")
    p.add_argument("--list-timezones",         action="store_true")

    # Load workshop-config.json if present (written by bootstrap)
    _cfg = {}
    _cfg_file = os.path.join(_HERE, "workshop-config.json")
    if os.path.exists(_cfg_file):
        try:
            _cfg = json.load(open(_cfg_file))
            print(f"  ✓ Loaded config: {_cfg_file}")
        except Exception:
            pass

    args = p.parse_args()

    if args.list_timezones:
        list_timezones()
        sys.exit(0)

    # Fill defaults from saved config where CLI left defaults untouched
    _def = {"host": "https://localhost:9200", "user": "elastic", "password": "changeme"}
    if args.host     == _def["host"]     and _cfg.get("host"):     args.host     = _cfg["host"]
    if args.user     == _def["user"]     and _cfg.get("user"):     args.user     = _cfg["user"]
    if args.password == _def["password"] and _cfg.get("password"): args.password = _cfg["password"]
    if not args.no_verify_ssl and _cfg.get("no_verify_ssl"):
        args.no_verify_ssl = _cfg["no_verify_ssl"]
    if not args.timezone and _cfg.get("timezone"):
        args.timezone = _cfg["timezone"]

    # Validate
    for name, val in [("--anomaly-chance", args.anomaly_chance),
                      ("--bot-attack-chance", args.bot_attack_chance)]:
        if not (0.0 <= val <= 1.0):
            print(f"ERROR: {name} must be between 0.0 and 1.0 (got {val})")
            sys.exit(1)

    tz = resolve_tz(args.timezone)

    ssl_opts = {"verify_certs": not args.no_verify_ssl, "ssl_show_warn": False}
    if args.no_verify_ssl:
        ssl_opts["ssl_assert_fingerprint"] = None
    es = Elasticsearch(args.host, basic_auth=(args.user, args.password), **ssl_opts)

    # ── Execution mode selection ──────────────────────────────────────────────
    # Explicit --livedata-only: skip backfill, go straight to live.
    # --backfill (alone):   run backfill, then stop.
    # --backfill --livedata: run backfill, then go live.
    # Neither --backfill nor --livedata-only: run both (default behaviour).

    run_bf   = args.backfill or (not args.livedata_only and not args.backfill and not args.livedata)
    run_live_after = args.livedata or (not args.backfill and not args.livedata_only)

    if args.livedata_only:
        run_bf         = False
        run_live_after = True

    bf_days = bf_apm_tpd = bf_edge_epd = bf_today_apm = bf_today_edge = 0

    if run_bf:
        bf_days, bf_apm_tpd, bf_edge_epd, bf_today_apm, bf_today_edge = run_backfill(
            host               = args.host,
            user               = args.user,
            password           = args.password,
            verify_ssl         = not args.no_verify_ssl,
            days               = args.days,
            apm_tpd            = args.apm_traces_per_day,
            edge_epd           = args.edge_events_per_day,
            anomaly_chance     = args.anomaly_chance,
            bot_attack_chance  = args.bot_attack_chance,
            tz                 = tz,
            workers            = args.workers,
            bulk_size_apm      = args.bulk_size_apm,
            bulk_size_edge     = args.bulk_size_edge,
            pb_threads         = args.pb_threads,
            pb_queue           = args.pb_queue,
        )

    if run_live_after:
        run_live(
            es                  = es,
            apm_tpd             = args.apm_traces_per_day,
            edge_epd            = args.edge_events_per_day,
            anomaly_chance      = args.anomaly_chance,
            bot_attack_chance   = args.bot_attack_chance,
            backfill_days       = bf_days,
            backfill_today_apm  = bf_today_apm,
            backfill_today_edge = bf_today_edge,
            bulk_size_apm       = args.bulk_size_apm,
            bulk_size_edge      = args.bulk_size_edge,
            pb_threads          = args.pb_threads,
            pb_queue            = args.pb_queue,
            tz                  = tz,
        )

    if not run_bf and not run_live_after:
        print("Nothing to do. Use --backfill, --livedata, or --livedata-only.")
        sys.exit(0)


if __name__ == "__main__":
    main()
